apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: team-splitter
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://gitlab.com/maxmukhanov/team-splitter-bot.git
    targetRevision: HEAD
    path: .manifests/kubernetes/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: team-splitter

  syncPolicy:
    syncOptions:
      - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
